AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 for hosting CTF'
Resources:
  CTFInstance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default: [setupBaseSoftware] #, setupDocker, setupCTFd, letsEncrypt] #, setupNetworking,setupUsers,suaas]
        setupBaseSoftware:
          packages:
            yum:
              wget: []
          commands:
            cmd01-test:
              command: 'pwd >> TESTER.txt'
            cmd02-yum-update:
              command: 'yum update -y'
        setupNetworking:
          commands:
            01cmd-setHostname:
              command: 'hostname $DOMAIN'
              env:
                DOMAIN: cody.public.ctf.com
            02cmd-etcHostname:
              command: 'echo "$DOMAIN" > /etc/hostname'
              env:
                DOMAIN: cody.public.ctf.com
            03cmd-etcHosts:
              command: 'echo "127.0.0.1 $DOMAIN" >> /etc/hosts'
              env:
                DOMAIN: cody.public.ctf.com
                #DOMAIN: 'CTF'
            ## Add some routes for the VDI networks
            04cmd-CreateEth1Config:
              command: 'cp -p /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-eth1'
            05cmd-Eth1CfgStatic:
              command: "sed -i 's/dhcp/static/' /etc/sysconfig/network-scripts/ifcfg-eth1"
            06cmd-Eth1CfgModDev:
              command: "sed -i 's/eth0/eth1/' /etc/sysconfig/network-scripts/ifcfg-eth1"
            07cmd-Eth1CfgModHwAddr:
              command: "sed -i '/HWADDR=.*/d' /etc/sysconfig/network-scripts/ifcfg-eth1"
            08cmd-Eth1CfgAddIP:
              command: 'sed -i "/ONBOOT=yes/a IPADDR=$PRIVIP" /etc/sysconfig/network-scripts/ifcfg-eth1'
              env:
                PRIVIP: !GetAtt Eth1.PrimaryPrivateIpAddress
            09cmd-CreateEth1RouteVDI:
              command: 'echo "10.111.4.0/22 via 10.70.76.1 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1' #Shared Services
            10cmd-CreateEth1RouteISC:
              command: 'echo "10.210.3.0/24 via 10.70.76.1 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1' #Shared Services
        setupUsers:
          commands:
            ## Running commands instead of user in order to kill the login
            01cmd-createUser:
              command: 'useradd secutil --shell /usr/sbin/nologin'
            02cmd-createCertGroup:
              command: 'groupadd --system certs'
            03cmd-addUserToCerts:
              command: 'usermod -G certs secutil'
            04cmd-createSecAdminGroup:
              command: 'groupadd secadmin'
            05cmd-addEc2-userSecAdmin:
              command: 'usermod -a -G secadmin ec2-user'
        setupDocker:
          commands:
            01cmd-addDockerRepo:
              command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
            02cmd-installDocker:
              command: 'yum install docker-ce docker-ce-cli containerd.io -y'
            03cmd-startDocker:
              command: 'systemctl start docker'
            04cmd-installDockerCompose:
              command: 'curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
            05cmd-chmodDockerCompose:
              command: 'chmod +x /usr/local/bin/docker-compose'
        setupCTFd:
          commands:
            00cmd-installWget:
              command: 'yum install wget -y'
            01cmd-wgetCTFd:
              command: 'wget -O /tmp/CTFd-v3.1.2.zip https://github.com/CodySchluenz/CTFd/archive/3.1.2.zip'
            02cmd-instalUnzip:
              command: 'yum install unzip -y'
            02cmd-unzip:
              command: 'unzip /tmp/CTFd-v3.1.2.zip -d /opt/secutil'
            04cmd-deleteCTFdZipFile:
              command: 'rm -f /tmp/CTFd-v3.1.2.zip'
            05cmd-chmod:
              command: 'chmod +x /opt/secutil/CTFd-v3.1.2'
            # 06cmd-accessToAdminConsole:
            #   command: 'sed -i "s!127.0.0.1!0.0.0.0!g" /opt/secutil/config.json'
            # 07cmd-createEndpointDir:
            #   command: 'mkdir /opt/secutil/static/endpoint'
            # 08cmd-changeEndpointPermissions:
            #   command: 'chmod 755 /opt/secutil/static/endpoint'
            # 09cmd-changeEndpointOwner:
            #   command: 'chown secutil /opt/secutil/static/endpoint'
        letsEncrypt:
          files:
            '/opt/letsEncrypt/getCert.sh':
              content: !Sub |
                #!/bin/bash

                domain="cody.public.ctf.com"

                # if certs exist delete them
                if [ -h '/opt/secutil/cert.pem' ]; then
                    rm /opt/secutil/cert.pem
                fi

                if [ -h '/opt/secutil/privkey.pem' ]; then
                    rm /opt/secutil/privkey.pem
                fi

                # get the cert
                /opt/letsEncrypt/certbot-auto --standalone --agree-tos --email codydps@gmail.com -d cody.public.ctf.com -n certonly

                # link the cert
                ln -s /etc/letsencrypt/live/cody.public.ctf.com/cert.pem /opt/secutil/cert.pem
                ln -s /etc/letsencrypt/live/cody.public.ctf.com/privkey.pem /opt/secutil/privkey.pem

                # Set permissions
                chgrp -R certs '/etc/letsencrypt'
                chmod -R g+rx '/etc/letsencrypt'
              mode: '000644'
              owner: secutil
              group: secadmin
          commands:
            01cmd-getCertbot:
              command: 'wget -P /opt/letsEncrypt https://dl.eff.org/certbot-auto'
            02cmd-chmodCertbot:
              command: 'chmod a+x /opt/letsEncrypt/certbot-auto'
            04cmd-startScript:
              command: "echo '#!/bin/bash' > /opt/letsEncrypt/getCert.sh"
            05cmd-setDomain:
              command: 'echo "domain=\"$DOMAIN\"" >> /opt/letsEncrypt/getCert.sh'
            05cmd-createShellScript:
              command: 'echo "/opt/letsEncrypt/certbot-auto --standalone --agree-tos --email codydps@gmail.com -d $DOMAIN -n certonly" >> /opt/letsEncrypt/getCert.sh'
              env:
                DOMAIN: cody.public.ctf.com
            06cmd-addExecuteToShellScript:
              command: 'chmod 755 /opt/letsEncrypt/getCert.sh'
            07cmd-exeShellScript:
              command: '/opt/letsEncrypt/getCert.sh'
            08cmd-changeCertDirGroup:
              command: 'chgrp -R certs /etc/letsencrypt/'
            09cmd-changeCertDirPerm:
              command: 'chmod -R g+rx /etc/letsencrypt/'
            10cmd-linkCert:
              command: 'ln -s /etc/letsencrypt/live/$DOMAIN/cert.pem /opt/secutil/cert.pem'
              env:
                DOMAIN: cody.public.ctf.com
            11cmd-linkKey:
              command: 'ln -s /etc/letsencrypt/live/$DOMAIN/privkey.pem /opt/secutil/privkey.pem'
              env:
                DOMAIN: cody.public.ctf.com
            12cmd-updateTLS:
              command: 'sed -i ''s/"use_tls" : false,/"use_tls" : true,/'' /opt/secutil/config.json'
            13cmd-updateCertPath:
              command: 'sed -i ''s/"cert_path" : ".*",/"cert_path" : "cert.pem",/'' /opt/secutil/config.json'
            14cmd-updateKeyPath:
              command: 'sed -i ''s/"key_path" : ".*"/"key_path" : "privkey.pem"/'' /opt/secutil/config.json'
            # Because of the change of spacing in the secUtil config
            15cmd-updateKeyPath:
              command: 'sed -i ''s/"key_path": ".*"/"key_path" : "privkey.pem"/'' /opt/secutil/config.json'
            16cmd-updatePort:
              command: 'sed -i ''s/"listen_url" : "0.0.0.0:80",/"listen_url" : "0.0.0.0:443",/'' /opt/secutil/config.json'
            17cmd-certRenewal:
              command: 'echo "/opt/letsEncrypt/certbot-auto renew > /dev/null" > /etc/cron.daily/renewcerts'
            18cmd-allowExeRenewcerts:
              command: 'chmod +x /etc/cron.daily/renewcerts'
        suaas:
          files:
            '/etc/systemd/system/secutil.service':
              content: !Sub |
                [Unit]
                Description=SecUtil Service
                After=network.target

                [Service]
                ExecStart=/opt/secutil/secutil
                Type=simple
                PIDFile=/var/run/secutil
                User=secutil
                WorkingDirectory=/opt/secutil

                [Install]
                WantedBy=default.target
              mode: '000644'
              owner: root
              group: root
          commands:
            ## user and service permissions
            01cmd-changeSecUtilDirOwner:
              command: 'chown -R secutil /opt/secutil /opt/secutil/'
            ## secUtil as a service (suaas)
            #02cmd-wgetSecUtilDaemon:
            #  command: 'wget https://gist.githubusercontent.com/immure/4ac4800189fd3e61f516838d0c35a519/raw/b95694856572b9e11263864711f0ba6eaf204625/gophish.service -O /etc/systemd/system/secutil.service'
            #03cmd-renameSecUtil:
            #  command: "sed -i 's/gophish/secutil/g' /etc/systemd/system/secutil.service"
            #04cmd-renameDescription:
            #  command: "sed -i 's/GoPhish/SecUtil/' /etc/systemd/system/secutil.service"
            05cmd-reloadDaemon:
              command: 'systemctl daemon-reload'
            06cmd-enableSecUtil:
              command: 'systemctl enable secutil'
            07cmd-startSecUtil:
              command: 'systemctl start secutil'

    DependsOn:
      - Eth0
      - Eth1
    Properties:
      ImageId: ami-098f16afa9edf40be
      KeyName: codysKeyPair
      InstanceType: 't2.micro'
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref Eth0
          DeviceIndex: '0'
        - NetworkInterfaceId: !Ref Eth1
          DeviceIndex: '1' 
      Tags:
        - Key: Name
          Value: CTF
        - Key: Dept
          Value: 'SecOps'
      EbsOptimized: false
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex

          # Kicking off script
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource CTFInstance --region ${AWS::Region}

          # Doesn't fire in the cfn-init section
          setcap CAP_NET_BIND_SERVICE=+eip /opt/secutil/CTFd-3.1.2
          newaliases
          init 6
  Eth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: 'eth0'
      GroupSet:
        - sg-06a059149a729109a             #SSH only
      SubnetId: subnet-65fd8f28            #Default Subnet
      Tags:
        - Key: Name
          Value: 'Interface 0'
        - Key: Interface
          Value: eth0
  Eth1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: 'eth1'
      GroupSet:
        - sg-06a059149a729109a             #SSH only
      SubnetId: subnet-65fd8f28            #Default Subnet
      Tags:
        - Key: Name
          Value: 'Interface 1'
        - Key: Interface
          Value: eth1
          
  IPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt IPAddress.AllocationId
      NetworkInterfaceId: !Ref Eth0
      
  DNSEntry:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z06983075CWAD5MB0CRJ
      Name: cody.public.ctf.com
      Type: A
      TTL: '300'
      ResourceRecords:
        - !Ref IPAddress
